// The catch catalogue: every fish and every oddity the lines can bring up.
//
// Pure data. Nothing here knows how a catch is rolled or drawn — js/game.js
// reads weights and sizes, js/art.js reads `art`. A new species is one entry.
//
//   id        stable key (saved in journals — never rename one)
//   loc       the location whose table it lives in
//   rarity    key into RARITY
//   w         optional weight multiplier on top of the rarity's own weight
//   kg        [min, max] size range
//   value     base sale value at a middling size
//   odd       true for things that are not fish (they don't count toward
//             "largest fish" and they don't fight)
//   ripple    only really turns up during a Mysterious Ripple (tiny weight otherwise)
//   art       drawing recipe for js/art.js

const RARITY = {
  common:    { name: "Common",    rank: 0, weight: 100, luck: 0,   fight: 0.18, colour: "#8a9aa6", badge: "●" },
  uncommon:  { name: "Uncommon",  rank: 1, weight: 34,  luck: 0.5, fight: 0.34, colour: "#2f9a5c", badge: "◆" },
  rare:      { name: "Rare",      rank: 2, weight: 11,  luck: 1,   fight: 0.52, colour: "#2d77c9", badge: "★" },
  veryrare:  { name: "Very Rare", rank: 3, weight: 3.6, luck: 1.3, fight: 0.68, colour: "#8a4fd0", badge: "✦" },
  legendary: { name: "Legendary", rank: 4, weight: 1.1, luck: 1.7, fight: 0.86, colour: "#d9901a", badge: "👑" },
};
const RARITY_ORDER = ["common", "uncommon", "rare", "veryrare", "legendary"];

// Shorthand art recipes. `c` = [back, belly, fin], `sh` = body shape.
const fish = (sh, c, extra = {}) => ({ k: "fish", sh, c, ...extra });

const CATCHES = [
  /* ---------------- Little Pond ---------------- */
  { id: "minnow", name: "Minnow", loc: "pond", rarity: "common", kg: [0.02, 0.12], value: 3,
    desc: "Small, silver and absolutely convinced it is a shark.",
    art: fish("slim", ["#8fa7b3", "#e9f1f4", "#b7c7cf"], { stripe: "#5f7b88" }) },
  { id: "perch", name: "Perch", loc: "pond", rarity: "common", kg: [0.3, 2.4], value: 7,
    desc: "Stripy, spiky, and would like a word with the manager.",
    art: fish("perch", ["#7c9a3c", "#f0e7b0", "#e4652e"], { bars: "#3f5222" }) },
  { id: "bluegill", name: "Bluegill", loc: "pond", rarity: "common", kg: [0.15, 1.2], value: 5,
    desc: "Named after its gills, which are more of a dark smudge. Nobody tell it.",
    art: fish("round", ["#4f7ea1", "#f3c46a", "#3b6280"], { bars: "#3a5e79", spot: "#1f3246" }) },
  { id: "carp", name: "Carp", loc: "pond", rarity: "common", kg: [1, 9], value: 10,
    desc: "Looks harmless. Has opinions.",
    art: fish("deep", ["#9a7a3e", "#e8d49a", "#8a5a2a"], { scales: true, whiskers: true }) },
  { id: "trout", name: "Trout", loc: "pond", rarity: "uncommon", kg: [0.5, 4], value: 22,
    desc: "Speckled all over, like it ran through a paint shop.",
    art: fish("torpedo", ["#6c7d52", "#efe2c4", "#8a8a5a"], { spots: "#3a3a2a" }) },
  { id: "bass", name: "Bass", loc: "pond", rarity: "uncommon", kg: [0.8, 5], value: 26,
    desc: "Mostly mouth. Uses all of it.",
    art: fish("bass", ["#4f7a3a", "#e7e2b8", "#5a7a3a"], { stripe: "#2e4a22", bigMouth: true }) },
  { id: "golden_trout", name: "Golden Trout", loc: "pond", rarity: "rare", kg: [0.6, 3.5], value: 130,
    desc: "Glitters like a birthday card. Knows exactly how pretty it is.",
    art: fish("torpedo", ["#e0a526", "#fff0a8", "#e5602c"], { stripe: "#d8472a", spots: "#a8661a", shine: true }) },
  { id: "rubber_duck", name: "Rubber Duck", loc: "pond", rarity: "rare", odd: true, kg: [0.05, 0.2], value: 18,
    desc: "Squeaks when frightened. Is always frightened.",
    art: { k: "duck" } },
  { id: "old_boot", name: "Old Boot", loc: "pond", rarity: "veryrare", w: 4, odd: true, kg: [0.4, 1.3], value: 2,
    desc: "Left foot. Surprisingly aerodynamic.",
    art: { k: "boot" } },
  { id: "koi_empress", name: "Koi Empress", loc: "pond", rarity: "legendary", kg: [3, 12], value: 650,
    desc: "Somebody's extremely expensive pet. She is not going back.",
    art: fish("deep", ["#f4f1ea", "#fffdf6", "#f1f1ea"], { patches: "#e2472a", scales: true, whiskers: true, fancyFins: true }) },

  /* ---------------- River Bend ---------------- */
  { id: "roach", name: "Roach", loc: "river", rarity: "common", kg: [0.15, 1.6], value: 15,
    desc: "Red eyes, silver coat. Looks like it stayed up far too late.",
    art: fish("round", ["#7e8e99", "#e3e9ec", "#d4533c"], { redEye: true }) },
  { id: "chub", name: "Chub", loc: "river", rarity: "common", kg: [0.5, 4], value: 20,
    desc: "Eats anything. Has eaten, at various times, a grape and a small sock.",
    art: fish("torpedo", ["#6d6f58", "#dcd8c0", "#b0703e"], { scales: true }) },
  { id: "rainbow_trout", name: "Rainbow Trout", loc: "river", rarity: "common", kg: [0.8, 5], value: 28,
    desc: "Wears a pink stripe everywhere. It's a whole look.",
    art: fish("torpedo", ["#6e8a6a", "#f1ece0", "#8a9a7a"], { stripe: "#e0708a", spots: "#39402e" }) },
  { id: "river_eel", name: "River Eel", loc: "river", rarity: "uncommon", kg: [0.4, 4], value: 46,
    desc: "Mostly tail, and the tail does not want to be here.",
    art: fish("eel", ["#4f5a3a", "#b9b58a", "#3e472c"]) },
  { id: "catfish", name: "Catfish", loc: "river", rarity: "uncommon", kg: [2, 22], value: 55,
    desc: "Has whiskers. Does not purr, despite being asked nicely.",
    art: fish("cat", ["#5e5a52", "#cfc6b0", "#4a463f"], { whiskers: true, spots: "#3a3731" }) },
  { id: "pike", name: "Pike", loc: "river", rarity: "uncommon", kg: [2, 16], value: 64,
    desc: "A torpedo with teeth and a grudge.",
    art: fish("pike", ["#4e6e3a", "#e6e2b0", "#7a6a3a"], { spots: "#d7d49a" }) },
  { id: "salmon", name: "Salmon", loc: "river", rarity: "rare", kg: [3, 18], value: 160,
    desc: "Swims UP rivers. On purpose. Every year.",
    art: fish("torpedo", ["#6e7f8e", "#f2d6cc", "#8a8f96"], { spots: "#384654", pinkBelly: true }) },
  { id: "lost_rod", name: "Lost Fishing Rod", loc: "river", rarity: "rare", odd: true, w: 0.8, kg: [0.4, 1.1], value: 85,
    desc: "Better than yours. Try not to think about it.",
    art: { k: "rod" } },
  { id: "tiger_trout", name: "Tiger Trout", loc: "river", rarity: "veryrare", kg: [1, 9], value: 420,
    desc: "Half brown trout, half brook trout, all swagger. Wears its stripes in a maze.",
    art: fish("torpedo", ["#b58a3a", "#f6e6b8", "#d8743a"], { wavy: "#5a3a12" }) },
  { id: "mystery_key", name: "Mysterious Key", loc: "river", rarity: "veryrare", odd: true, ripple: true, kg: [0.05, 0.3], value: 240,
    desc: "Opens something, somewhere. Probably.",
    art: { k: "key" } },
  { id: "silver_king", name: "Silver King Salmon", loc: "river", rarity: "legendary", kg: [10, 32], value: 1500,
    desc: "The river's oldest resident. Has seen things. Won't talk about them.",
    art: fish("torpedo", ["#b9c8d4", "#ffffff", "#d7e1e8"], { spots: "#7f93a3", shine: true, crown: true }) },

  /* ---------------- Crystal Lake ---------------- */
  { id: "walleye", name: "Walleye", loc: "lake", rarity: "common", kg: [1, 6], value: 60,
    desc: "Huge glassy eyes. Can see you. Can see everything.",
    art: fish("pike", ["#8a8a4a", "#efe7b8", "#9a8a4a"], { bigEye: true, bars: "#5a5a2a" }) },
  { id: "largemouth", name: "Largemouth Bass", loc: "lake", rarity: "common", kg: [2, 9], value: 75,
    desc: "Could fit a tennis ball in there. Please don't try.",
    art: fish("bass", ["#3f6e34", "#ecebc0", "#4a6e34"], { stripe: "#23421c", bigMouth: true }) },
  { id: "lake_trout", name: "Lake Trout", loc: "lake", rarity: "common", kg: [2, 15], value: 85,
    desc: "Cold, deep and patient. Like a very good fridge.",
    art: fish("torpedo", ["#55666e", "#e8e4d8", "#6e7a7e"], { spots: "#d9dccf" }) },
  { id: "garden_gnome", name: "Garden Gnome", loc: "lake", rarity: "uncommon", odd: true, w: 0.5, kg: [1, 3], value: 40,
    desc: "Was fishing, apparently. Caught nothing.",
    art: { k: "gnome" } },
  { id: "northern_pike", name: "Northern Pike", loc: "lake", rarity: "uncommon", kg: [4, 22], value: 150,
    desc: "The river pike's bigger, grumpier cousin from up north.",
    art: fish("pike", ["#35603a", "#e2e6b8", "#6a6a30"], { spots: "#cfe0a0" }) },
  { id: "giant_carp", name: "Giant Carp", loc: "lake", rarity: "uncommon", kg: [8, 38], value: 170,
    desc: "It's the regular carp's opinions, but louder.",
    art: fish("deep", ["#8a6630", "#e2c888", "#7a4a20"], { scales: true, whiskers: true }) },
  { id: "sturgeon", name: "Sturgeon", loc: "lake", rarity: "rare", kg: [15, 90], value: 520,
    desc: "Armoured like a knight and older than the dinosaurs' grandparents.",
    art: fish("sturgeon", ["#5d6770", "#c9c9c0", "#4a525a"], { plates: "#e0dccc", whiskers: true }) },
  { id: "albino_sturgeon", name: "Albino Sturgeon", loc: "lake", rarity: "veryrare", kg: [20, 100], value: 1600,
    desc: "Pale as a ghost, and just as good at vanishing.",
    art: fish("sturgeon", ["#eee8e0", "#ffffff", "#e3d8d0"], { plates: "#f7c9c0", whiskers: true, pinkEye: true }) },
  { id: "muskie", name: "Muskie the Dock-Eater", loc: "lake", rarity: "legendary", kg: [15, 42], value: 3200,
    desc: "Local legend says it ate a whole jetty. The jetty has not commented.",
    art: fish("pike", ["#6d7a3a", "#f0ecc0", "#8a6a2a"], { bars: "#3d4a1c", crown: true }) },

  /* ---------------- Coastal Pier ---------------- */
  { id: "mackerel", name: "Mackerel", loc: "pier", rarity: "common", kg: [0.3, 2], value: 190,
    desc: "Tiger stripes, very shiny, always in a hurry.",
    art: fish("tuna", ["#2f7a8a", "#eef4f2", "#2a5a66"], { wavy: "#123a44" }) },
  { id: "flathead", name: "Flathead", loc: "pier", rarity: "common", kg: [0.5, 4], value: 230,
    desc: "Someone sat on it once. It never recovered.",
    art: fish("flat", ["#9a8060", "#efe0c4", "#8a6e4e"], { spots: "#5e4a36" }) },
  { id: "snapper", name: "Snapper", loc: "pier", rarity: "common", kg: [1, 10], value: 290,
    desc: "Pink, proud, and snaps at compliments.",
    art: fish("deep", ["#e0675e", "#ffd7c6", "#d4524a"], { spots: "#7ab8e0" }) },
  { id: "squid", name: "Squid", loc: "pier", rarity: "uncommon", kg: [0.5, 5], value: 380,
    desc: "Ten arms, three hearts, zero chill.",
    art: { k: "squid", c: ["#e3a3a8", "#f7d8d8", "#c46a78"] } },
  { id: "crab", name: "Crab", loc: "pier", rarity: "uncommon", kg: [0.4, 3], value: 420,
    desc: "Walks sideways out of every argument.",
    art: { k: "crab", c: ["#e0522e", "#f7a45c", "#9a2e1a"] } },
  { id: "pufferfish", name: "Pufferfish", loc: "pier", rarity: "uncommon", kg: [0.5, 3], value: 460,
    desc: "Inflates when embarrassed. Is embarrassed now.",
    art: fish("puffer", ["#d9b760", "#fff3c8", "#c79a40"], { spots: "#6a5220" }) },
  { id: "lobster", name: "Lobster", loc: "pier", rarity: "rare", kg: [1, 9], value: 1100,
    desc: "Fancy. Knows it's fancy. Has claws about it.",
    art: { k: "lobster", c: ["#2f4f7a", "#5d7fae", "#1c3150"] } },
  { id: "bottle", name: "Message in a Bottle", loc: "pier", rarity: "veryrare", odd: true, kg: [0.3, 0.8], value: 650,
    desc: "It says: \"Help! I am stuck in a bottle.\" Hmm.",
    art: { k: "bottle" } },
  { id: "blue_groper", name: "Big Blue Groper", loc: "pier", rarity: "legendary", kg: [8, 40], value: 6500,
    desc: "Friendly, enormous, and extremely blue. Follows divers around like a puppy.",
    art: fish("deep", ["#2f64b4", "#8fb8ea", "#1e4a8a"], { bigMouth: true, crown: true }) },

  /* ---------------- Open Sea ---------------- */
  { id: "mahi", name: "Mahi-Mahi", loc: "open", rarity: "common", kg: [5, 25], value: 640,
    desc: "So good they named it twice.",
    art: fish("mahi", ["#2aa36a", "#f2d240", "#2a8ad0"], { spots: "#1a5a9a" }) },
  { id: "barracuda", name: "Barracuda", loc: "open", rarity: "common", kg: [3, 22], value: 720,
    desc: "All teeth, no manners.",
    art: fish("pike", ["#6c7e8e", "#e8ecef", "#4e5e6e"], { bars: "#3e4e5e", teeth: true }) },
  { id: "tuna", name: "Tuna", loc: "open", rarity: "uncommon", kg: [20, 160], value: 1400,
    desc: "Built like a submarine. Swims like one too, if submarines were rude.",
    art: fish("tuna", ["#23406e", "#e8ecf0", "#e8c23a"], { finlets: "#f0cc3a" }) },
  { id: "swordfish", name: "Swordfish", loc: "open", rarity: "rare", kg: [40, 260], value: 3600,
    desc: "Brought a sword to a fish fight. Technically allowed.",
    art: fish("sword", ["#4a5a7a", "#dfe2ea", "#3a4a6a"]) },
  { id: "marlin", name: "Marlin", loc: "open", rarity: "rare", kg: [60, 360], value: 4300,
    desc: "Fastest thing in the sea, and it has a sail. Show-off.",
    art: fish("sword", ["#1f4f8e", "#e2e8f0", "#2a60b0"], { sail: true, bars: "#6aa0e0" }) },
  { id: "sea_turtle", name: "Sea Turtle", loc: "open", rarity: "veryrare", kg: [30, 200], value: 2800,
    desc: "Carefully unhooked and waved off. She did not say thank you, but she thought it.",
    art: { k: "turtle", c: ["#5d8a4a", "#c9b37a", "#3e6a2e"] }, release: true },
  { id: "treasure_chest", name: "Treasure Chest", loc: "open", rarity: "veryrare", odd: true, kg: [8, 30], value: 9000,
    desc: "Locked. Heavy. Rattles in a very promising way.",
    art: { k: "chest" } },
  { id: "sunfish", name: "Ocean Sunfish", loc: "open", rarity: "legendary", kg: [200, 1000], value: 16000,
    desc: "Shaped like a fish that gave up halfway. Weighs as much as a car.",
    art: fish("sunfish", ["#8c96a2", "#dfe4ea", "#7a8490"]) },

  /* ---------------- Deep Sea ---------------- */
  { id: "lanternfish", name: "Lanternfish", loc: "deep", rarity: "common", kg: [0.03, 0.4], value: 1900,
    desc: "Carries its own night-light. Very sensible.",
    art: fish("slim", ["#2a3450", "#5a6a8a", "#1e2640"], { glow: "#7ff0ff", glowDots: true }) },
  { id: "deep_eel", name: "Deep-Sea Eel", loc: "deep", rarity: "common", kg: [2, 16], value: 2700,
    desc: "Like a river eel, but it has read some very dark poetry.",
    art: fish("eel", ["#2c2438", "#5a4a6a", "#1c1628"], { glow: "#c080ff" }) },
  { id: "fossil", name: "Fossil", loc: "deep", rarity: "uncommon", odd: true, w: 0.7, kg: [2, 12], value: 3100,
    desc: "Very old. Very still. Extremely good at hide and seek.",
    art: { k: "fossil" } },
  { id: "anglerfish", name: "Anglerfish", loc: "deep", rarity: "uncommon", kg: [2, 30], value: 4200,
    desc: "Goes fishing, with its own face. Respect.",
    art: fish("angler", ["#3a2e3e", "#6a5a66", "#2a2030"], { lure: "#a8ffea", teeth: true }) },
  { id: "pirate_coin", name: "Pirate Coin", loc: "deep", rarity: "rare", odd: true, kg: [0.02, 0.05], value: 6200,
    desc: "One doubloon. The other 9,999 must be nearby.",
    art: { k: "coin" } },
  { id: "giant_squid", name: "Giant Squid", loc: "deep", rarity: "rare", kg: [50, 275], value: 12500,
    desc: "Probably best not to ask where it came from.",
    art: { k: "squid", c: ["#b0413e", "#e38a78", "#7a2626"], giant: true } },
  { id: "coelacanth", name: "Ancient Fish", loc: "deep", rarity: "veryrare", kg: [20, 90], value: 26000,
    desc: "Was supposed to be extinct. Did not get the memo.",
    art: fish("ancient", ["#2e4a6e", "#8aa0b8", "#23405e"], { spots: "#e0e8f0" }) },
  { id: "ancient_relic", name: "Ancient Relic", loc: "deep", rarity: "veryrare", odd: true, ripple: true, kg: [3, 15], value: 32000,
    desc: "Hums quietly. Please keep it on a high shelf.",
    art: { k: "relic" } },
  { id: "starlight_jelly", name: "Starlight Jelly", loc: "deep", rarity: "legendary", kg: [1, 8], value: 85000,
    desc: "Glows in colours that don't have names yet.",
    art: { k: "jelly", c: ["#b98cff", "#7ff0ff", "#ff9ee0"] } },
];

const CATCH = Object.fromEntries(CATCHES.map((c) => [c.id, c]));

// The middle of a catch's size range, which is where `value` is pinned.
function catchMid(c) { return (c.kg[0] + c.kg[1]) / 2; }
